nodeLinker: pnp

# Tell Yarn that whenever @nrwl/tao is installed, it needs to
# implicitly depend on nx so `require('nx')` works under PnP
packageExtensions:
  "@nrwl/tao@*":
    dependencies:
      nx: "*"


yarnPath: .yarn/releases/yarn-4.9.1.cjs
